-- ============================================================================
--  HEROBOOK — Contenu Loup Solitaire 01 (généré automatiquement)
--  Ne pas modifier à la main : régénérer avec
--      node scripts/generer-sql-contenu.cjs
-- ============================================================================

BEGIN;

DELETE FROM public.lw_sections WHERE livre_slug = 'loup-solitaire-01';

INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '1', 'La nuit du monastère Kaï', NULL, 'Un cri déchire la nuit. Vous ouvrez les yeux dans le dortoir glacial du monastère Kaï et, avant même d''avoir repris vos esprits, une odeur de poix brûlée vous saisit à la gorge. Par la fenêtre, le ciel est rouge. Des silhouettes sombres courent entre les bâtiments, des torches à la main, et leurs hurlements rauques se répondent sans fin.

Le cœur battant, vous roulez hors de votre paillasse. Les autres novices ont disparu. Sur le mur de pierre, l''ombre tremblante d''une créature armée d''une hache passe et repasse — puis s''éloigne.

Le monastère qui vous a formé est en train de mourir. Que faites-vous ?', NULL, '[{"texte":"Foncer vers la salle des Maîtres pour leur porter secours","vers":"12"},{"texte":"Rassembler votre équipement d''initié et fuir vers la falaise","vers":"2"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '2', 'La salle d''armes', NULL, 'La salle d''armes n''a pas encore été atteinte par le feu. Vous décrochez votre hache de la Râtelier des Novices, devenue votre unique arme, puis vous bourrez votre Sac à Dos d''un Repas. Dans le coffre de la chambrée des Sacs, vous prenez une bourse de Pièces d''Or et la Carte du Sommerlund que les Maîtres remettent à chaque initié qui part en épreuve.

Dans une niche de pierre, un rayon de lune éclaire une dernière étagère, sous laquelle sont éparpillés des effets ayant appartenu à vos aînés. Il neige de la cendre. Vous pouvez emporter une seule de ces choses.', NULL, '[{"texte":"Emporter votre butin et sortir par la petite porte de l''étable","vers":"4"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '4', 'La cour des morts', NULL, 'Vous sortez par la petite porte de l''étable et manquez de glisser sur les marches : la cour du monastère est jonchée de corps. La pluie fine fait fumer les torches renversées. Tout en haut du mur d''enceinte, des formes ailées tournoient lentement, comme des rapaces.

Des voix rauques, toutes proches, échangent des ordres dans cette langue sifflante qui vous fait froid dans le dos. Une patrouille remonte le sentier. Vous n''avez que quelques secondes pour décider.', NULL, '[{"texte":"Suivre votre Sixième Sens, qui vous souffle de filer vers le nord-est (Discipline du Sixième Sens)","vers":"131","requis":{"discipline":"sixieme-sens"},"montreToujours":true},{"texte":"Se faufiler entre les corps et descendre vers la route du sud","vers":"100"},{"texte":"Se plaquer contre le mur et attendre le passage de la patrouille","vers":"60"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '12', 'La salle des Maîtres', NULL, 'Vous traversez à grandes enjambées le couloir des « Étoiles », que les fumées rendent irrespirable. La porte de la salle des Maîtres est arrachée de ses gonds. À l''intérieur, c''est un charnier : vos maîtres gisent sur les dalles, frappés dans leur sommeil, leurs robes blanches souillées de suie et de sang.

Au centre de la pièce, le vieux Maître Kaï en chef repose comme un homme qui aurait simplement fermé les yeux. Sa main est tendue vers la porte, comme s''il avait voulu vous avertir. Une gargouille au regard de braise s''écrase dans l''embrasure : vous vous jetez sous une table basse et l''impact projette autour de vous un nuage de pierre brûlante (vous perdez 2 points d''ENDURANCE).

Il n''y a plus rien à sauver ici. Le monastère n''appartient plus aux hommes. Il vous faut partir, et vivre pour porter la nouvelle.', '2', NULL, NULL, NULL, '{"endurance":-2}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '44', 'La mine abandonnée', NULL, 'Le calme revient. Banedon est assis contre la paroi, sa robe déchirée, une longue estafilade à l''épaule. Il sourit malgré tout : « Tu t''es battu comme un Seigneur Kaï, garçon. Il reste peut-être un espoir pour ce royaume. »

Dans un coin de la galerie, il a rassemblé ce qu''il a pu trouver : un rouleau de corde solide et deux flacons d''un liquide vert sombre. « Du laumspur, dit-il. Tu en boiras une dose après un combat, quand tu tiendras à peine debout : cela vaut tous les médecins du Sommerlund. »

Avant de repartir, il vous regarde gravement : « Tu portes deux armes, maintenant. Prends-en une seule, celle qui te va le mieux : l''encombrement tue plus de fuyards que les lames. »', '113', NULL, NULL, NULL, '{"objets":[{"id":"corde"},{"id":"potion-laumspur","quantity":2},{"id":"torche"},{"id":"briquet"},{"id":"epee-courte","optionnel":true}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '45', 'Le Kraan', '/lonewolf/pdf/colored/kraan.png', 'Vous ramassez une poignée de cailloux et vous les lancez vers la créature ailée. Elle pique vers vous dans un sifflement de cuir et de plumes, toutes griffes dehors : c''est exactement ce que vous vouliez. Un Kraan mort ne préviendra personne.', '46', NULL, '{"nom":"Kraan","habilete":16,"endurance":24,"emoji":"🦇","description":"Une créature ailée au service du Roi-Sorcier, environ deux fois plus grande qu''un aigle. Ses griffes sont enduites de poison.","image":"/lonewolf/portraits/kraan.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '46', 'La fiole du cavalier', NULL, 'La créature s''écrase dans la rivière dans un grand geyser d''eau noire. Sur son harnais, vous trouvez une petite besace de cuir imperméable : six Pièces d''Or et un parchemin couvert d''une écriture runique que vous ne savez pas lire. Vous emportez le tout et traversez le pont sans plus attendre.', '142', NULL, NULL, NULL, '{"or":6,"objets":[{"id":"message"}],"drapeau":"a_message"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '60', 'Dans l''ombre du mur', NULL, 'Vous vous aplatissez derrière un sarcophage et respirez à peine. Les Giaks passent si près que vous sentez leur haleine fétide. Au moment où vous croyez le danger passé, vous marchez sur une branche qui craque.

Une des créatures s''arrête. Elle renifle. Votre main se referme sur le manche de votre hache.', '100', NULL, NULL, '{"type":"jet-hasard","titre":"Un craquement de branche","texte":"La sentinelle hésite, puis reprend sa route. Vous attendez que le dernier souffle de la nuit efface le bruit de leurs pas.","ton":"danger","branches":{"0-4":{"texte":"Le Giak vous a entendu : il abaisse sa lance vers vous. Rendez-vous au 100.","vers":"100"},"5-9":{"texte":"La créature hausse les épaules et s''éloigne en grommelant. Vous profitez de l''ombre pour gagner le sentier sud. Rendez-vous au 131.","vers":"131"}}}'::jsonb, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '64', 'Le gué aux loups', NULL, 'Le chemin des haies vous mène à une rivière étroite et profonde, franchie par un vieux pont de pierre. De l''autre côté, un cheval sellé tourne en rond près d''un chariot abandonné, hennissant de terreur. Entre vous et lui, deux Loups Maudits, maigres et affamés, se disputent un quartier de viande.

Au-dessus de la rivière, une ombre immense tourne en cercles : un Kraan, l''une de ces créatures ailées au service du Roi-Sorcier. Elle n''a pas encore repéré votre présence — mais elle finira par le faire.', NULL, '[{"texte":"Foncer, attraper le cheval et traverser le pont au galop","vers":"70"},{"texte":"Traverser la rivière à la nage, plus bas, entre les roseaux","vers":"522"},{"texte":"Vous glisser dans les roseaux et attendre que tout ce petit monde s''en aille (Discipline du Camouflage)","vers":"142","requis":{"discipline":"camouflage"},"montreToujours":true},{"texte":"Abattre les loups et vous emparer du cheval","vers":"71"},{"texte":"Attirer le Kraan au sol et le combattre avant qu''il ne donne l''alerte","vers":"45"}]'::jsonb, NULL, NULL, '{"repasObligatoire":true}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '65', 'La dépouille du Gourgaz', NULL, 'Le monstre s''abat dans un fracas d''os et de cuir. Les cavaliers vous acclament, puis repartent au galop — ils doivent couvrir la caravane.

Sur le corps, vous trouvez une bourse de dix Pièces d''Or et un flacon de verre noir, soigneusement enveloppé de cuir. Le chef de la troupe, avant de s''éloigner, vous crie : « C''est de l''Alether ! Garde-le pour le jour où tu devras tuer beaucoup plus fort que toi ! »', '66', NULL, NULL, NULL, '{"or":10,"objets":[{"id":"potion-alether"}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '66', 'Le Vordak', '/lonewolf/pdf/colored/vordak.png', 'Vous rangez le flacon dans votre Sac à Dos. C''est alors que le silence se fait : tout à coup, plus un oiseau, plus un criquet. Les chevaux de la caravane, cent mètres plus loin, refusent d''avancer.

Une forme descend de la colline, enveloppée dans une cape rouge. Sous le capuchon, vous ne voyez qu''un masque d''os pâle, et deux lueurs rouges là où devraient être les yeux. Un Vordak — l''un de ces serviteurs morts-vivants que les Maîtres Kaï redoutaient entre tous. Sa voix résonne directement dans votre crâne : « Le dernier petit loup… enfin seul. »

Si vous ne possédez pas le Bouclier Psychique, son souffle mental vous infligera un malus d''Habileté tant que vous ne l''aurez pas abattu.', NULL, '[{"texte":"Lever votre arme et aller au-devant de lui","vers":"67"},{"texte":"Disparaître dans les fourrés et le laisser passer (jet de hasard)","vers":"68"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '67', 'Le duel des ombres', '/lonewolf/pdf/colored/vordak.png', 'Vous foncez. Le Vordak glisse vers vous sans que ses pieds touchent vraiment le sol, et la froideur de son esprit s''insinue dans vos tempes comme une aiguille de glace. Vous serrez les dents et vous frappez.', '69', NULL, '{"nom":"Vordak","habilete":18,"endurance":26,"immunisePsychique":true,"malusPsychique":2,"emoji":"💀","description":"Un serviteur mort-vivant du Roi-Sorcier. Immunisé à la Puissance Psychique ; son attaque mentale coûte 2 points d''Habileté, sauf si vous possédez le Bouclier Psychique.","image":"/lonewolf/portraits/vordak.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '68', 'Le souffle du Vordak', NULL, 'Vous vous jetez dans les orties. Le Vordak s''arrête, humant l''air — puis, sans se retourner, il reprend sa descente vers la route. Vous retenez votre souffle.

Quand vous osez enfin lever la tête, il a disparu. Mais quelque chose cloche : vos mains tremblent, et une migraine froide s''est installée derrière vos yeux.', NULL, NULL, NULL, '{"type":"jet-hasard","titre":"Le Vordak vous cherche","texte":"Une voix sans visage murmure votre nom dans votre tête. Vous priez pour que la forêt vous garde quelques secondes de plus.","ton":"mystere","branches":{"0-4":{"texte":"Le Vordak vous trouve. Il n''y aura pas de fuite cette fois : rendez-vous au 67.","vers":"67"},"5-9":{"texte":"Le silence revient. Vous perdez 2 points d''Endurance, mais vous êtes vivant. Rendez-vous au 64.","endurance":-2,"vers":"64"}}}'::jsonb, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '69', 'La gemme noire', NULL, 'Le Vordak se brise comme un bloc de glace et sa cape vide s''affaisse dans la poussière. À l''endroit où son cœur aurait dû battre, une gemme noire roule sur la route. Elle pulse d''une lueur mauvaise, et vous sentez qu''elle vaut une fortune.

Vous la ramassez, ou vous la jetez. Peu importe : la route de Toran n''a pas fini de vous réclamer.', NULL, '[{"texte":"Emporter la Gemme de Vordak (elle attire l''œil des serviteurs du Roi-Sorcier)","vers":"64","effets":{"objets":[{"id":"gemme-vordak"}],"drapeau":"gemme_vordak"}},{"texte":"La jeter dans la rivière et poursuivre votre route","vers":"64"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '70', 'La course du pont', NULL, 'Vous bondissez, saisissez les rênes et vous jetez sur le dos du cheval affolé. Les loups hurlent, l''ombre du Kraan s''abat — trop tard : vous êtes déjà sur l''autre rive, et la bête ailée ne peut vous suivre entre les arbres.

Le cheval vous portera jusqu''aux collines de Holmgard.', '142', NULL, NULL, NULL, '{"drapeau":"a_cheval"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '71', 'Les deux loups', NULL, 'Vous n''avez pas le temps de ruser : les bêtes vous ont senti. Elles abandonnent leur charogne et viennent de front, l''une à gauche, l''autre à droite, exactement comme les chasseurs du Roi-Sorcier leur ont appris à le faire.', '142', NULL, '{"nom":"Meute de Loups Maudits","habilete":14,"endurance":24,"emoji":"🐺","description":"Deux chiens de guerre du Roi-Sorcier, attaquant ensemble : leurs valeurs sont cumulées, comme le veut la règle des combats multiples.","image":"/lonewolf/portraits/loup-maudit.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '86', 'La ferme incendiée', NULL, 'Vous sautez dans le fossé et hissez la petite sur vos épaules tandis que le garçon s''accroche à votre tunique. Au moment où vous les déposez auprès d''une vieille femme, un grondement monte de derrière la ferme : un chien de guerre, aussi haut qu''un poney, la gueule écumante, un reste de chaîne brisée au collier.

Le garçon hurle. Vous le poussez derrière le mur et vous empoignez votre arme.', '87', NULL, '{"nom":"Loup Maudit","habilete":13,"endurance":16,"emoji":"🐺","description":"Un chien de guerre du Roi-Sorcier, dressé à la chasse aux hommes. Sa chaîne brisée fouette l''air.","image":"/lonewolf/portraits/loup-maudit.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '87', 'Ce que la ferme a laissé', NULL, 'La bête s''effondre dans un dernier souffle, et un grand silence tombe sur la ferme. Le père des enfants vous remercie d''une voix brisée et vous guide jusqu''à l''atelier : la maison a brûlé, mais la réserve du fond est intacte.

Vous y trouvez un Marteau de Guerre de belle facture, deux Repas et une petite réserve de Pièces d''Or. La famille refuse tout en retour ; elle dit simplement : « Que les dieux vous gardent, Seigneur Kaï. »', '188', NULL, NULL, NULL, '{"or":8,"objets":[{"id":"marteau-de-guerre","optionnel":true},{"id":"repas","quantity":2}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '90', 'Le sentier des contrebandiers', NULL, 'Vous repérez, sous les fougères, une trace à peine visible : deux ornières parallèles, des branches cassées à hauteur d''épaule, et l''odeur ténue d''un feu de charbon. Un sentier de contrebandiers, qui coupe tout le bois des Bruyères et permet d''éviter la route.

Vous le suivez pendant des heures. Le soir, vous débouchez près d''un ancien abri de bûcherons où deux hommes, un chien et une mule montent la garde.

Ils vous voient. L''un d''eux pose la main sur son coutelas ; l''autre vous détaille, puis crache par terre : « Un Kaï ? Il en reste donc un. » Vous expliquez. Le plus vieux hoche la tête : « Les Giaks ont brûlé mon village, la semaine dernière. Prends ce que tu veux dans le barda, gamin. Et si tu croises ces chiens, fais-leur payer. »

Ils vous offrent deux Repas et vous indiquent le raccourci qui rejoint la caravane à la nuit tombée.', '200', NULL, NULL, NULL, '{"objets":[{"id":"repas","quantity":2}],"drapeau":"contrebandiers"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '100', 'La patrouille', '/lonewolf/pdf/colored/gloks.png', 'Le sentier descend sous les pins. Vous n''avez pas fait cent pas que des grognements éclatent derrière vous : trois Giaks ont relevé votre piste. Leurs yeux rouges luisent sous des casques de fer bosselé, leurs lances sont barbelées de crocs d''animaux.

L''un d''eux pousse un cri de chasse et se détache du groupe. Il sera sur vous dans un instant.', NULL, '[{"texte":"L''attendre de pied ferme et combattre","vers":"101"},{"texte":"Vous jeter derrière les rochers et disparaître dans la fougère (Discipline du Camouflage)","vers":"102","requis":{"discipline":"camouflage"},"montreToujours":true},{"texte":"Détaler vers la lisière de la forêt en espérant les semer","vers":"103"}]'::jsonb, NULL, NULL, '{"repasObligatoire":true}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '101', 'Premier sang', NULL, 'Vous bondissez par-dessus une souche et faites face. Le Giak, emporté par son élan, ouvre sa garde — et vous n''avez pas l''intention de laisser passer cette chance. Donnez le premier coup avant de poursuivre le combat.', '102', NULL, '{"nom":"Giak","habilete":9,"endurance":9,"bonusJoueur":4,"emoji":"👹","description":"Un soldat giak, petit mais hargneux, armé d''une lance barbelée et d''un bouclier de cuir.","image":"/lonewolf/portraits/giak.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '102', 'La lisière de Fryelund', NULL, 'Vous courez longtemps, sans regarder en arrière, jusqu''à ce que les murs du monastère ne soient plus qu''une lueur rouge au sommet de la colline. Devant vous s''ouvre la forêt de Fryelund : des pins immenses dont les aiguilles vous griffent le visage, et une humidité froide qui sent la résine et la mousse.

Vous êtes le dernier des Seigneurs Kaï. Derrière vous, l''armée du Roi-Sorcier. Devant, trois cents kilomètres de forêt et de route jusqu''à Holmgard, la capitale du Sommerlund. Et dans votre poche, un secret qui pourrait sauver le royaume.

Vous vous accordez quelques minutes, le dos contre un tronc, le temps de reprendre votre souffle.', NULL, '[{"texte":"Trancher vers le nord-est, en suivant la lumière de l''aube","vers":"131"},{"texte":"Suivre le ruisseau vers l''est et longer les collines","vers":"131"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '103', 'Sous les ronces', NULL, 'Vous vous jetez dans un fourré de ronces si épais que vos poursuivants perdent votre trace en quelques minutes. Vous rampez sur une dizaine de mètres, le visage en sang, avant de déboucher sur un petit sentier de chevreuil.

En vous relevant, votre pied heurte quelque chose de dur sous la mousse : une bourse de cuir oubliée là, contenant six Pièces d''Or. Un peu plus loin, dans un bouquet de fougères, une tablette de savon parfumé embaume encore. Vous emportez les deux, avec le sentiment étrange que la forêt, elle, ne vous veut pas de mal.', '131', NULL, NULL, NULL, '{"or":6,"objets":[{"id":"savon"}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '113', 'Le départ de Banedon', NULL, 'Dehors, la nuit commence à tomber et une lueur bleue danse au sommet de la colline. Le vaisseau de Banedon ressemble à un grand oiseau de toile et de verre, posé entre les pins. Il embarque, puis se penche une dernière fois vers vous.

« Ceci appartenait à mon ordre, dit-il en détachant de son cou un pendentif d''argent en forme d''étoile à sept branches. Elle n''éclaire pas les routes, Loup Solitaire — elle éclaire les cœurs. Garde-la, et souviens-toi que tu n''es pas seul. »

Le pendentif de l''Étoile de Cristal se referme dans votre paume, encore chaud. Dans un souffle, le vaisseau s''arrache au sol et disparaît vers le nord. Vous êtes seul, avec une étoile autour du cou.', '213', NULL, NULL, NULL, '{"objets":[{"id":"cristal-etoile","message":"Le pendentif de l''Étoile de Cristal"}],"drapeau":"a_cristal_etoile"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '129', 'Les portes de Holmgard', '/lonewolf/pdf/colored/holmgard.png', 'Vous atteignez la porte du Sud au moment où la garde la referme derrière un dernier convoi de réfugiés. Une foule effrayée se presse sous les voûtes. Les gardes, épuisés, refoulent des familles entières.

Vous vous frayez un chemin dans la cohue jusqu''à un officier en cotte de mailles, qui observe la scène d''un air sombre. Il porte l''écu du Roi.

Que faites-vous ?', NULL, '[{"texte":"Aller droit à lui et décliner votre identité de Seigneur Kaï","vers":"318"},{"texte":"Le prendre à part discrètement et raconter ce que vous avez vu","vers":"318"},{"texte":"Traverser la ville par vous-même jusqu''au palais royal","vers":"319"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '131', 'L''homme sur la route', '/lonewolf/pdf/colored/banedon.png', 'Vous marchez depuis deux heures quand un bruit nouveau résonne dans la forêt : des cris, des coups de sifflet, puis une détonation sèche qui fait s''envoler tout un envol de corneilles.

Sur le sentier, un jeune homme en robe bleu ciel brodée d’étoiles court vers vous en trébuchant. Il est essoufflé ; des étincelles bleues crépitent encore au bout de ses doigts. Derrière lui, vous entendez les grognements d''une meute de Giaks.

Il vous voit, lève la main et crie : « Loup Solitaire ! Ils ont brûlé le monastère ! Fuis, garçon — non, attends… aide-moi, et je te donnerai de quoi traverser ce royaume vivant. »', NULL, '[{"texte":"Lui crier de se jeter derrière vous et faire face aux Giaks","vers":"281"},{"texte":"Se mettre à couvert et le laisser poursuivre seul","vers":"133"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '133', 'Le prix de la prudence', NULL, 'Vous vous glissez derrière un tronc mort. Le jeune magicien passe en haletant, les Giaks sur ses talons. Il se retourne une dernière fois, cherche votre aide du regard, et vous voyez la déception traverser son visage — puis un projectile le frappe à l''épaule et il s''effondre dans les fougères.

Les Giaks, trop occupés à fouiller son corps, ne vous remarquent pas. Vous repartez le ventre serré d''une honte que rien ne lavera, et il vous semble que la forêt s''est refermée derrière vous pour toujours.', '281', NULL, NULL, NULL, '{"drapeau":"abandonne_banedon"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '142', 'Holmgard, enfin', '/lonewolf/pdf/colored/holmgard.png', 'Au sommet de la dernière colline, vous la voyez enfin : Holmgard, la capitale du Sommerlund. Ses remparts blancs montent vers le ciel, ses tours portent les couleurs or et pourpre du Roi, et dans la brume du matin, des milliers de fumées s''élèvent des faubourgs. Le cœur serré, vous pensez aux ruines noires du monastère.

Mais des colonnes de fumée montent aussi de la ville basse. L''armée du Roi-Sorcier est plus proche que vous ne le pensiez.

Deux itinéraires s''offrent à vous : la route royale, large et surveillée, ou le raccourci du Cimetière des Anciens, un vieux champ de tombes que les Sommerlendiens évitent par superstition.', NULL, '[{"texte":"Couper par le Cimetière des Anciens","vers":"153"},{"texte":"Prendre la route royale et rejoindre les portes de la ville","vers":"129"}]'::jsonb, NULL, NULL, '{"repasObligatoire":true}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '153', 'Le Cimetière des Anciens', '/lonewolf/pdf/colored/cimetiere.png', 'Le Cimetière des Anciens est un champ de mausolées penchés, rongés par le lierre. Les tombes les plus vieilles datent de l''arrivée des Sommerlendiens, il y a plus de mille ans. L''air y est étrangement immobile.

Devant vous, un escalier de pierre descend sous un mausolée ouvert. Une odeur de renfermé et de cire froide en monte. Au-dessus de la porte, une inscription en vieux sommerlien : « Ici repose la garde du premier Roi. Que celui qui descend sans y être invité descende pour toujours. »

Quelque part dans votre dos, des cors de guerre sonnent : les Giaks ne sont pas loin.', NULL, '[{"texte":"Écouter votre Sixième Sens avant de descendre (Discipline du Sixième Sens)","vers":"154","requis":{"discipline":"sixieme-sens"},"montreToujours":true},{"texte":"Descendre hardiment dans la crypte","vers":"154"},{"texte":"Presser le pas et rejoindre les portes de la ville","vers":"129"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '154', 'La crypte du Premier Roi', '/lonewolf/pdf/colored/crypte.png', 'Votre lampe de poche improvisée éclaire des rangées de sarcophages sculptés. Vous avancez entre deux haies de statues de gardes, jusqu''au fond de la salle, où se dresse un trône de pierre noire.

Sur le trône est assis un squelette en armure, un casque doré sur le crâne, et dans sa main osseuse repose une grande clé d''or. Vous n''avez pas fait trois pas qu''un craquement retentit derrière vous : quelque chose de grand s''est réveillé dans l''ombre des tombeaux.', '155', NULL, '{"nom":"Rejeton de crypte","habilete":16,"endurance":16,"emoji":"☠️","description":"Un gardien de tombeau animé par une magie ancienne, bien plus vieux que le Roi-Sorcier."}'::jsonb, NULL, '{"repasObligatoire":true}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '155', 'La Clé d''Or', NULL, 'Le gardien s''effondre en un tas d''os et de poussière. Vous gravissez les marches du trône, et prenez la Clé d''Or dans la main du Premier Roi. Elle est lourde, froide, et porte gravé le sceau de la maison de Sommerlund.

En vous retournant, vous apercevez une trappe dérobée, par laquelle vous remontez à l''air libre, derrière les murs de la ville.', '129', NULL, NULL, NULL, '{"objets":[{"id":"cle-or","message":"La Clé d''Or du Premier Roi"}],"drapeau":"a_cle_or"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '157', 'La route de Toran', NULL, 'La route de Toran est une longue artère de terre battue qui traverse le Sommerlund du nord au sud. En temps de paix, on y croise des marchands, des ménestrels et des moines en voyage. Aujourd''hui, c''est un fleuve de misère.

Des centaines de villageois fuient vers le sud, poussant des charrettes, portant des enfants endormis, traînant des bêtes affolées. Les visages sont gris de cendre. Personne ne parle. Au loin, dans votre dos, une colonne de fumée noire marque l''emplacement de votre monastère.

Un cri perçant domine soudain la rumeur : deux enfants sont tombés dans un fossé, et un chariot renversé les sépare du reste de la colonne. Les parents hurlent, mais la foule avance, elle ne s''arrêtera pas.', NULL, '[{"texte":"Vous précipiter pour sortir les enfants du fossé","vers":"86"},{"texte":"Rejoindre la caravane et poursuivre vers le sud sans vous arrêter","vers":"207"},{"texte":"Vous fondre dans la colonne sous l''apparence d''un paysan (Discipline du Camouflage)","vers":"200","requis":{"discipline":"camouflage"},"montreToujours":true},{"texte":"Repérer un sentier de contrebandiers qui coupe à travers bois (Discipline de l''Orientation)","vers":"90","requis":{"discipline":"orientation"},"montreToujours":true}]'::jsonb, NULL, NULL, '{"repasObligatoire":true}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '188', 'Les cavaliers de Toran', NULL, 'À l''aube, un bruit de tonnerre fait trembler la route : une troupe de cavaliers descend au galop, bannières au vent. Ce sont les Chevaliers de Toran, ce qu''il reste de la garnison du nord. Ils s''arrêtent auprès de la caravane et leur chef, un colosse à barbe rousse, annonce qu''il faut se hâter vers Holmgard.

Plus loin, sur la gauche, une rangée de haies d''aubépine longe la rivière : un chemin discret, que les chevaux ne peuvent emprunter.

Derrière le rideau d''arbres, à l''écart, une silhouette démesurée vous observe : une créature osseuse, haute comme trois hommes, montée sur des jambes de reptile. Les réfugiés ne l''ont pas vue. Vous, si.', NULL, '[{"texte":"Rejoindre les cavaliers et chevaucher à leur côté (les prévenir)","vers":"255"},{"texte":"Emprunter seul le chemin des haies et vous éloigner de la bête","vers":"64"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '200', 'La charrette du marchand', NULL, 'Une charrette vous rattrape, tirée par un cheval efflanqué. Le marchand, un petit homme rond vêtu d''un manteau rapiécé, vous fait monter d''un geste. Il s''appelle Griff et prétend n''avoir jamais quitté la route de Toran de sa vie.

« Les cavaliers, là-bas, ne valent rien pour toi, dit-il en mâchant une racine. Ils vont s''arrêter toutes les deux lieues pour rassurer les fuyards. Si tu veux sauver le royaume, mon garçon, coupe par les collines et longe les aubépines. Tu croiseras des bêtes du Roi-Sorcier, forcément. Mais tu arriveras. »

Il vous laisse descendre un peu plus loin, après vous avoir offert un Repas et une information précieuse : à Holmgard, c''est la porte du Sud qu''il faut viser, celle que garde l''Hermine.', '188', NULL, NULL, NULL, '{"objets":[{"id":"repas"}],"drapeau":"indication_porte_sud"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '207', 'La caravane', NULL, 'Vous aidez une vieille femme à pousser sa charrette pendant une heure, puis deux, jusqu''à ce que la nuit tombe sur la route. Elle vous parle du roi, des Seigneurs Kaï, et de son fils qui est garde à Holmgard. « Si tu arrives là-bas, cherche la porte du Sud, mon garçon. Dis-leur que tu viens de la part d''Alinne. »

Elle vous offre un Repas, et vous vous endormez au milieu du bétail, bercé par les roues et les sabots.', '200', NULL, NULL, NULL, '{"objets":[{"id":"repas"}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '213', 'Le tunnel', NULL, 'Au matin, la forêt de Fryelund se resserre. Vous suivez un ancien chemin de bûcherons quand une odeur de charogne vous arrête net : devant vous, un tunnel de pierre taillée s''enfonce dans le flanc d''un coteau, et quelque chose y a traîné une carcasse de cerf.

La galerie est le raccourci le plus court vers la route de Toran ; la contourner vous coûterait une journée, et les Giaks ratissent la forêt. Des bruits lourds, humides, montent des profondeurs. Vous cherchez dans votre Sac à Dos.', NULL, '[{"texte":"Allumer la torche et descendre dans le tunnel (nécessite une Torche et un Briquet)","vers":"214","requis":{"sac":"torche"},"montreToujours":true},{"texte":"Descendre à l''aveugle, une main sur la paroi","vers":"215"},{"texte":"Faire un long détour par la crête, à découvert","vers":"331"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '214', 'La créature des profondeurs', '/lonewolf/pdf/colored/gluatre.png', 'La torche s''allume dans un crépitement. La lumière vous sauve la vie : elle aveugle la chose qui vous attendait dans le noir. Elle a la forme d''une chenille de la taille d''une charrette, couverte d''écailles visqueuses et terminée par une gueule circulaire hérissée de dents.

La torche bat en retrait la créature, mais elle frappe à l''aveugle, et ses coups suffisent à briser la pierre.', '216', NULL, '{"nom":"Gluatre des profondeurs","habilete":17,"endurance":7,"immunisePsychique":true,"malusPsychique":3,"malusEvitePar":"torche","emoji":"🐛","description":"Un prédateur aveugle des galeries. La torche annule les 3 points d''Habileté qu''il inflige par sa terreur visqueuse.","image":"/lonewolf/portraits/gluatre.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '215', 'Dans le noir absolu', '/lonewolf/pdf/colored/gluatre.png', 'Vous avancez à tâtons, une main sur la paroi glacée. Votre respiration est si forte qu''elle couvre tous les bruits… tous, non : un frottement humide approche quelque part devant vous, et vous n''avez ni torche ni repère pour vous défendre.

La chose vous frappe avant même que vous ne la voyiez. Vous roulez sur le sol, votre hache frappant au hasard dans la nuit la plus totale.', '216', NULL, '{"nom":"Gluatre des profondeurs","habilete":17,"endurance":7,"immunisePsychique":true,"malusPsychique":3,"emoji":"🐛","description":"Sans lumière, la créature conserve son avantage : 3 points d''Habileté de moins pour vous.","image":"/lonewolf/portraits/gluatre.webp"}'::jsonb, NULL, '{"endurance":-3}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '216', 'L''or du mineur', NULL, 'La créature se replie en sifflant dans une galerie latérale. Vous continuez, le cœur battant, et débouchez dans une ancienne chambre d''exploitation. Un squelette de mineur git contre une poutre, une bourse à la ceinture, et à côté de lui un poignard de belle facture, encore gainé de cuir.

Vous prenez les vingt Pièces d''Or et le poignard, puis vous remontez vers la lumière du jour par une cheminée effondrée.', '331', NULL, NULL, NULL, '{"or":20,"objets":[{"id":"poignard","optionnel":true}]}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '255', 'Le Gourgaz', '/lonewolf/pdf/colored/gourgaz.png', 'Vous vous portez à hauteur du chef de la troupe et lui désignez la chose du doigt. Il devient livide. « Un Gourgaz ! siffle-t-il. Ces monstres commandent les meutes du Roi-Sorcier. » Il tire son épée et fait signe aux siens de protéger la caravane.

Le Gourgaz se dresse alors de toute sa hauteur, et le premier cheval s''effondre, la gorge ouverte. Vous bondissez au sol. C''est vous qu''il regarde maintenant.', '65', NULL, '{"nom":"Gourgaz","habilete":20,"endurance":30,"immunisePsychique":true,"emoji":"🦎","description":"Le plus redoutable des serviteurs du Roi-Sorcier sur la route de Toran. Immunisé à la Puissance Psychique.","image":"/lonewolf/portraits/gourgaz.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '281', 'L''embuscade de la colline', '/lonewolf/pdf/colored/gloks.png', 'L''homme s''appelle Banedon, et il est apprenti de la Guilde des Magiciens de Toran. « Mon vaisseau est posé sur la colline, là-haut, dit-il en désignant la crête. Ses moteurs sont gelés. Il me faut encore une heure, et ils seront là dans dix minutes. »

En haut de la colline, une trappe s''ouvre dans l''herbe brune : c''est l''entrée d''une ancienne mine. Vous y poussez Banedon juste au moment où les premiers Giaks jaillissent des fougères. Vous vous retournez, hache en main, le dos à l''ouverture.', '44', NULL, '{"nom":"Giaks de la confrérie","habilete":13,"endurance":20,"emoji":"👺","description":"Deux Giaks d''élite, revêtus de plaques de cuir clouté. Ils se battent ensemble, en se couvrant l''un l''autre.","image":"/lonewolf/portraits/giaks.webp"}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '318', 'La salle du Roi', '/lonewolf/pdf/colored/roi-ulnar.png', 'Le palais de Holmgard est une fourmilière : officiers, messagers, prêtres et guérisseurs se croisent dans les escaliers. On vous conduit dans la grande salle, où le Roi Ulnar de Sommerlund, encore en armure, écoute ses généraux autour d''une carte immense.

Quand vous entrez, un silence pesant tombe. Le vieux Roi vous regarde — la hache maculée de sang, la tunique déchirée, l''étoile d''argent à votre cou — et son visage se décompose avant même que vous n''ayez parlé.

« Les Seigneurs Kaï… ? » demande-t-il.

C''est le moment. Tout ce que vous allez dire décidera peut-être de l''avenir du Sommerlund.', NULL, '[{"texte":"Tout raconter, du monastère en flammes jusqu''à la route de Toran","vers":"350"},{"texte":"Remettre au Roi le pendentif de Banedon et la Clé d''Or du Premier Roi (Objets Spéciaux requis)","vers":"351","requis":{"special":"cristal-etoile","objet":"cle-or"},"montreToujours":true},{"texte":"Vous tenir à l''écart : la gemme du Vordak, dans votre sac, chuchote des choses (Gemme de Vordak)","vers":"352","requis":{"special":"gemme-vordak"},"montreToujours":true}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '319', 'Seul dans la ville basse', NULL, 'Vous vous engagez dans les ruelles de Holmgard, mais la ville est en état de siège : chaque carrefour est barré par des barricades, chaque rue surveillée par des milices nerveuses. On vous arrête trois fois. La troisième, un sergent vous plaque contre un mur et vous demande d''où vient cette hache couverte de sang.

Il faut vous expliquer, et vite.', NULL, NULL, NULL, '{"type":"jet-hasard","titre":"Le sergent vous fouille","texte":"Vous cherchez vos mots tandis qu''un attroupement se forme autour de vous.","ton":"danger","branches":{"0-4":{"texte":"On vous traîne en cellule. On refuse de vous croire. Le lendemain, le Roi-Sorcier franchit les remparts : vous avez perdu trop de temps.","vers":"520"},"5-9":{"texte":"Un vieux garde reconnaît en vous le disciple du monastère et se porte garant. On vous escorte jusqu''au palais.","vers":"318"}}}'::jsonb, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '331', 'Le bois des bûcherons', NULL, 'Vous émergez enfin du tunnel et respirez à pleins poumons. La forêt de Fryelund n''est plus qu''un rideau vert derrière vous.

Sur votre droite, une cabane de bûcherons s''accroche à un énorme chêne, à quatre mètres du sol. On y accède par une échelle de corde. Une lanterne s''y balance : quelqu''un est chez lui, ou bien y a-t-il trouvé refuge.

Vous entendez la rumeur lointaine d''une rivière, et, plus loin encore, celle de la route de Toran.', NULL, '[{"texte":"Grimper à l''échelle de corde et frapper à la porte","vers":"332"},{"texte":"Continuer sans s''arrêter vers la route de Toran","vers":"157"}]'::jsonb, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '332', 'Le bûcheron', NULL, 'Un vieil homme voûté vous ouvre, une hachette à la main. Il vous examine longuement, puis vous fait signe d''entrer. « J''ai vu la lumière sur la colline, cette nuit, grommelle-t-il. Le monastère, hein ? »

Il ne pose pas d''autre question. Il vous tend une miche de pain, une couverture de laine, et un marteau de guerre qu''il décroche du mur. « Prends. Je n''ai plus l''âge de m''en servir. »

Quand vous redescendez à l''aube, il vous crie une dernière chose : « Sur la route de Toran, évite les convois de soldats. Les Giaks sont partout, et il y a pire que les Giaks, mon garçon. »', '157', NULL, NULL, NULL, '{"objets":[{"id":"repas","quantity":2},{"id":"couverture"},{"id":"marteau-de-guerre","optionnel":true}],"drapeau":"a_marteau"}'::jsonb, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '350', 'Le Serment de Sommerlund', '/lonewolf/pdf/colored/roi-ulnar.png', 'Vous parlez. Du dortoir en flammes, des Maîtres massacrés dans leur sommeil, de la mine où Banedon a failli mourir, de la route de Toran et de ses enfants dans le fossé. Le Roi Ulnar vous écoute sans vous interrompre, les mains crispées sur le pommeau de son épée.

Quand vous avez terminé, un long silence traverse la salle. Puis le vieux Roi se lève, et devant toute sa cour, il dit d''une voix qui porte jusqu''aux voûtes :

« Le Sommerlund est orphelin de ses Seigneurs Kaï. Mais il est resté un disciple — un disciple qui a traversé trois cents kilomètres de pays conquis pour m''apporter la vérité. Qu''il soit désormais Loup Solitaire, Seigneur Kaï de plein droit, et qu''il porte notre dernière espérance. La guerre commence demain, et je jure devant vous tous : tant qu''un seul Sommerlendien vivra, la lumière ne s''éteindra pas. »

Au-dehors, les cloches de Holmgard sonnent le rassemblement. Votre première aventure s''achève ici ; la suivante commence à l''aube.', NULL, NULL, NULL, NULL, NULL, 'victoire', 'Le Serment de Sommerlund');
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '351', 'L''Étoile et la Clé', '/lonewolf/pdf/colored/roi-ulnar.png', 'Vous posez sur la table de chêne du Roi deux choses : la Clé d''Or du Premier Roi, encore froide, et le pendentif de l''Étoile de Cristal que Banedon vous a confié dans la lumière bleue de la colline.

Le Roi Ulnar se penche. Sa main tremble légèrement lorsqu''elle effleure l''étoile à sept branches. « Mon père portait un sceau identique, dit-il. La Confrérie de l''Étoile de Cristal n''a donc pas disparu — et voici la Clé que les Anciens confièrent aux Seigneurs Kaï pour qu''elle ne tombe jamais aux mains des Ténèbres. »

Il se tourne vers vous, et pour la première fois depuis votre arrivée, il sourit.

« Tu n''apportes pas seulement une nouvelle, Loup Solitaire. Tu apportes une alliance. Ce soir, Holmgard n''est plus seule. Demain, nous nous battrons. »

On vous remet une cape blanche à liseré d''or : la cape d''un Seigneur Kaï de la nouvelle génération. Sur les remparts, les cloches de la ville sonnent à l''espérance.', NULL, NULL, NULL, NULL, NULL, 'victoire', 'L''Étoile et la Clé (fin remarquable)');
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '352', 'Le regard de la gemme', NULL, 'Vous reculez d''un pas. La gemme noire pulse contre votre flanc, de plus en plus vite, comme un cœur. Autour de vous, les conversations s''arrêtent : les flammes des chandelles s''inclinent toutes dans votre direction.

Un craquement sec au plafond, et une forme noire tombe au milieu de la salle, épée au poing. Ce n''est pas un Giak : c''est un assassin du Roi-Sorcier, venu reprendre ce qu''on lui a volé — et tuer le dernier témoin du massacre.', '350', NULL, '{"nom":"Assassin du Roi-Sorcier","habilete":16,"endurance":20,"immunisePsychique":true,"emoji":"🗡️","description":"Un tueur envoyé pour récupérer la gemme. Il frappe vite et sans un mot."}'::jsonb, NULL, NULL, NULL, NULL);
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '520', 'Trop tard', NULL, 'La ville tombe avant l''aube. Des cris, des incendies, et cette même odeur de poix brûlée que vous connaissez trop bien. Le Roi-Sorcier est entré dans Holmgard, et personne n''a prévenu le Roi.

Vous avez survécu, mais le Sommerlund, lui, ne survit pas. Il ne reste rien d''un messager arrivé trop tard.', NULL, NULL, NULL, NULL, NULL, 'mort', 'Le message trop tardif');
INSERT INTO public.lw_sections (livre_slug, numero, titre, image, texte, suite, choix, combat, evenement, effets, fin, nom_fin) VALUES ('loup-solitaire-01', '522', 'Les eaux noires', NULL, 'Vous entrez dans l''eau et le froid vous coupe le souffle. Le courant est bien plus violent qu''il n''y paraît : la rivière de Toran, gonflée par les pluies, vous emporte vers les rapides.

Vous vous débattez, mais vos bottes s''alourdissent, votre Sac à Dos se remplit d''eau, et les cris des loups s''éloignent derrière vous. Sur la rive, personne ne vous verra disparaître. Le dernier Seigneur Kaï du Sommerlund se noie dans une rivière anonyme, à cent kilomètres de la capitale.', NULL, NULL, NULL, NULL, NULL, 'mort', 'Les eaux noires de Toran');

COMMIT;

-- Contrôle :
-- SELECT COUNT(*) FROM public.lw_sections WHERE livre_slug = 'loup-solitaire-01';
